#!/bin/bash

help() {
  echo "Usage:"
  echo "  zproject add <repository> [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  project::add "$@"
}

run() {
  core "$@"
}

run "$@"
