#!/bin/bash

help() {
  echo "Merge - merges remote upstream changes into your local current branch"
  echo ""
  echo "Usage:"
  echo "  project merge <upstream_branch>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local upstream_branch=$1
  if [ -z "$upstream_branch" ]; then
    os::inquirer upstream_branch "text" "Please input upstream branch" true "master"
  fi

  local branch=$(git::branch)
  log::info "[$(timestamp)] current branch: $branch ..."
  if [ -n "$upstream_branch" ]; then
    log::info "[$(timestamp)] upstream branch: $upstream_branch ..."
  fi

  log::info "[$(timestamp)] start to merge remote branch to local ..."
  project::merge "$upstream_branch"
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to to merge remote branch to local."
    return 1
  fi

  log::success "[$(timestamp)] succeed to merge remote branch to local."
}

run() {
  core "$@"
}

run "$@"
