#!/bin/bash

help() {
  echo "Pull - pull source code from remote repository"
  echo ""
  echo "Usage:"
  echo "  project pull [remote] [branch or tag...]"
  echo ""
  echo "Description:"
  echo "  For Git repositories: pulls from remote Git repository"
  echo "  For Git-SVN repositories: fetches and rebases from SVN"
  echo ""
  echo "Options:"
  echo "  -h, --help  display help information"
  echo ""
  echo "Example:"
  echo "  project pull"
  echo "  project pull origin"
  echo "  project pull github"
  echo "  project pull origin master"
  echo "  project pull origin v1.0.0"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  project::pull "$@"
}

run() {
  core $@
}

run $@
