#!/bin/bash

help() {
  echo "Push - push source code to remote git repository with current branch"
  echo ""
  echo "Usage:"
  echo "  project push [branch or tag...]"
  echo ""
  echo "Options:"
  echo "  -h, --help  display help information"
  echo ""
  echo "Example:"
  echo "  project push"
  echo "  project push master"
  echo "  project push v1.0.0"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  project::push "$@"
}

run() {
  core $@
}

run $@
