#!/bin/bash

help() {
  echo "Push - push source code to remote git repository with current branch"
  echo ""
  echo "Usage:"
  echo "  project push [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  project::push
}

run() {
  core $@
}

run $@
