#!/bin/bash

help() {
  echo "Push - push source code to remote repository"
  echo ""
  echo "Usage:"
  echo "  project push [remote] [branch or tag...]"
  echo ""
  echo "Description:"
  echo "  For Git repositories: pushes to remote Git repository"
  echo "  For Git-SVN repositories: commits to SVN repository"
  echo ""
  echo "Options:"
  echo "  -h, --help  display help information"
  echo ""
  echo "Example:"
  echo "  project push"
  echo "  project push origin"
  echo "  project push github"
  echo "  project push origin master"
  echo "  project push origin v1.0.0"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  project::push "$@"
}

run() {
  core $@
}

run $@
