#!/bin/bash

help() {
  echo "Usage:"
  echo "  project release"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local currence_path=$(pwd)
  log::info "[$(timestamp)] release project (dir: $currence_path)..."

  project::release "$currence_path"
}

run() {
  core "$@"
}

run "$@"
