#!/bin/bash

help() {
  echo "Usage:"
  echo "  zproject run <command> [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  project::run_command "$@"
}

run() {
  core $@
}

run $@
