#!/bin/bash

help() {
  echo "Sync - sync current branch and put local to remote"
  echo ""
  echo "Usage:"
  echo "  project sync [options...] [upstream_branch]"
  echo ""
  echo "Options:"
  echo "    --no-push   Don't push the branch to remote"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    return 0
  fi

  log::info "[$(timestamp)] start to sync branch with remote <=> local ..."
  project::sync "$@"
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to sync branch with remote <=> local."
    return 1
  fi

  log::success "[$(timestamp)] succeed to sync branch with remote <=> local."
}

run() {
  core "$@"
}

run "$@"
