#!/bin/bash

project::add() {
  local repository=$1
  local args=${@:2}

  if [ -z "$repository" ]; then
    log::error "[$(timestamp)] repository is required"
    exit 1
  fi

  os::gpm add "$@"
}

export -f project::add
