#!/bin/bash

# project::commit 推送代码到远程
project::commit() {
  local is_need_commit=true

  log::info "[$(timestamp)] pre commit ..."
  if [ "$(git::is_ready_to_commit)" = "false" ]; then
    local add="Add_all_files"
    local nadd="commit_only_without_add"
    local quit="cancel"
    local add_types=("$add" "$nadd" "$quit")

    local add_type="$1"

    if [ -z "$add_type" ]; then
      os::inquirer add_type "select" add_types "发现未add文件"
      if [ "$?" != "0" ]; then
        return $?
      fi
    fi

    case $add_type in
    "$add")
      # add 文件后提交
      git add .
      ;;
    "$nadd")
      # 不 add 直接提交
      ;;
    esac
  fi

  if [ "$is_need_commit" = "true" ]; then
    log::info "[$(timestamp)] start to commit ..."
    gpm commit
    if [ "$?" != "0" ]; then
      log::info "[$(timestamp)] failed to commit ..."
      return 1
    fi

    log::info "[$(timestamp)] succeed to commit ..."
  else
    log::info "[$(timestamp)] not necessary to commit, ignore ..."
  fi
}

export -f project::commit
