#!/bin/bash

# project::merge_upstream 如果是 feature，说明在开发功能，提交时可以自动 merge 远端当前峰值
project::merge_upstream() {
  local upstream_branch=$1
  local tmp_error=$(os::tmp_file)

  if [ -z "$upstream_branch" ]; then
    log::error "[$(timestamp)] upstream branch is required"
    return 1
  fi

  os::git fetch origin >>/dev/null 2>$tmp_error
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp) failed to fetch origin."
    cat $tmp_error
    return 1
  fi

  os::git merge origin/${upstream_branch} --quiet >>/dev/null 2>$tmp_error
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to merge origin branch"
    cat $tmp_error
    return 1
  fi
}

export -f project::merge_upstream
