#!/bin/bash

project::pull() {
  local branch=$(git::branch)
  local upstream_branch=$1

  if [ -n "$upstream_branch" ]; then
    log::info "[$(timestamp)] upstream branch: $upstream_branch ..."
  fi

  # 如果远程存在当前分支
  log::info "[$(timestamp)] start to check whether remote branch($branch) exist ..."
  if [ "$(git::has_branch ${branch})" != "true" ]; then
    log::error "[$(timestamp)] remote branch($branch) not found"
    return 1
  fi

  log::info "[$(timestamp)] pulling remote branch ..."
  os::git pull origin $branch # --quiet
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to pull remote branch to local, please check whether have confict."
    return 1
  fi
}

export -f project::pull
