#!/bin/bash

project::push() {
  # not a git repository
  if [ ! -d "$PWD/.git" ]; then
    log::error "[$(timestamp)] current work directory is not a git repository."
    return 1
  fi

  log::info "[$(timestamp)] ready to push ..."

  local branch=$(git::branch)
  if [ -z "$branch" ]; then
    log::error "[$(timestamp)] cannot get local branch."
    return 1
  fi

  log::info "[$(timestamp)] start to push local branch to remote ..."
  os::git push origin $branch
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to push local branch to remote."
    return 1
  fi

  log::success "[$(timestamp)] succeed to push local branch to remote."
}

export -f project::push
