#!/bin/bash

project::push() {
  local branch="$1"
  local is_git_repo=false

  local tmp_dir=$(pwd)
  while [ "$tmp_dir" != "/" ]; do
    if [ -d "$tmp_dir/.git" ]; then
      is_git_repo=true
      break
    fi

    tmp_dir=$(dirname $tmp_dir)
  done

  # not a git repository
  if [ "$is_git_repo" != "true" ]; then
    log::error "[$(timestamp)] current work directory is not a git repository."
    return 1
  fi

  log::info "[$(timestamp)] ready to push ..."

  if [ "$branch" = "" ]; then
    branch=$(git::branch)
    if [ -z "$branch" ]; then
      log::error "[$(timestamp)] cannot get local branch."
      return 1
    fi
  fi

  log::info "[$(timestamp)] start to push local branch to remote ..."
  os::git push origin $branch
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to push local branch to remote."
    return 1
  fi

  log::success "[$(timestamp)] succeed to push local branch to remote."
}

export -f project::push
