#!/bin/bash

project::push() {
  local remote="$1"
  local branch="$2"
  local repo_type=$(git_svn::detect_repo_type)
  
  if [ "$repo_type" = "none" ]; then
    log::error "[$(timestamp)] current work directory is not a git repository."
    return 1
  fi
  
  
  case $repo_type in
    "git")
      # 原有的 Git 逻辑
      log::info "[$(timestamp)] ready to push ..."
      
      if [ -z "$remote" ]; then
        remote="origin"
      fi
      
      if [ "$branch" = "" ]; then
        branch=$(git::branch)
        if [ -z "$branch" ]; then
          log::error "[$(timestamp)] cannot get local branch."
          return 1
        fi
      fi
      
      log::info "[$(timestamp)] start to push local branch to remote ..."
      os::git push $remote $branch
      if [ "$?" != "0" ]; then
        log::error "[$(timestamp)] failed to push local branch to remote."
        return 1
      fi
      ;;
    "git-svn")
      # Git SVN 逻辑
      git_svn::push
      return $?
      ;;
    *)
      log::error "[$(timestamp)] unsupported repository type: $repo_type"
      return 1
      ;;
  esac
  
  log::success "[$(timestamp)] succeed to push to remote."
}

export -f project::push
