#!/bin/bash

project::release() {
  # apply proxy
  net::using_smart_proxy

  # ./bin/zmicro/release
  local custom_release="$(project::find_command release)"
  if [ -n "$custom_release" ]; then
    project::run_command release "${@:2}"
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)] failed to release project."
      return 1
    fi
    return 0
  fi

  local path=$1
  if [ -z "$path" ]; then
    log::error "[$(timestamp)] project path is required."
    return 1
  fi
  
  cd $path

  if [ "$(string::starts_with $currence_path $ZMICRO_HOME)" = "true" ]; then
    zmicro release .
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)] failed to release project."
      return 1
    fi
  else
    os::gpm release
    # if [ "$?" != "0" ]; then
    #   log::error "[$(timestamp)] failed to release project."
    #   return 1
    # fi
  fi
}

export -f project::release
