#!/bin/bash

help() {
  echo "Master - switch to develop branch"
  echo ""
  echo "Usage:"
  echo "  project switch develop"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  git checkout develop
}

run() {
  core "$@"
}

run "$@"
